getUserInfo cache & avatar size
baraja-core/gravatar pull request #5
Opened 2021-08-10 17:19 UTC by filipjakub

2021-08-10 21:06 UTC, janbarasek commented
@filipjakub Zvládl bys provést rebase tvojí větve a vyřešit konflikty?

2021-08-10 21:08 UTC, filipjakub commented
> @filipjakub Zvládl bys provést rebase tvojí větve a vyřešit konflikty?

Jakoby ještě jsem to nedělal, ale rád se o to pokusím.

2021-08-10 21:22 UTC, filipjakub commented
Musím to dělat přes command-line, nebo stačí vyřešit ty rozdíly v tom web editoru? @janbarasek

2021-08-10 21:29 UTC, janbarasek requested changes
Jinak je to moc pěkný!

2021-08-10 21:29 UTC, janbarasek commented on src/Gravatar.php
> +			} else {
Else lze vynechat a kód napsat přímo, protože pokud se nevyhodila výjimka, tak kód bude pokračovat vždy validně.

2021-08-10 21:29 UTC, janbarasek commented on src/Gravatar.php
> +					return 'https://www.gravatar.com/avatar/' . urlencode($hash) . '?s=' . $size . '&d=' . urlencode($this->defaultIcon);
Tento zápis mi dává v tomto kontextu smysl, akorát až budeš mít hodně parametrů, tak se budou těžko kombinovat.

Raději implementuj na začátku metody proměnnou `$params = []`, do které budeš přidávat postupně hodnoty.

Obsahem pak může být například:

```php
$params = [
   's' => 24,
   'd' => '...',
];
```

Sestavení parametrů na URL pak uděláš funkcí `http_build_query()`.

2021-08-10 21:29 UTC, janbarasek commented on src/Gravatar.php
> +		$this->cache = new Cache($storage, 'User Info');
Namespace by měl být spíše obecný:

```suggestion
		$this->cache = new Cache($storage, 'gravatar');
```

2021-08-10 21:30 UTC, janbarasek commented
@filipjakub Jde to udělat jednoduše v PhpStormu. Návod je tady: https://www.jetbrains.com/help/phpstorm/apply-changes-from-one-branch-to-another.html

Před rebasem musíš pullnout změny z mainu.

2021-08-10 22:05 UTC, filipjakub commented on src/Gravatar.php
> +					return 'https://www.gravatar.com/avatar/' . urlencode($hash) . '?s=' . $size . '&d=' . urlencode($this->defaultIcon);
`$params['d'] = urlencode($this->defaultIcon);

return 'https://www.gravatar.com/avatar/' . urlencode($hash) . '?' . urldecode(http_build_query($params));`

Je nutné použít `urlencode()` a poté `decode()`, když používám ten `http_build_query()`, nebo stačí bez toho? @janbarasek

2021-08-11 08:25 UTC, janbarasek commented on src/Gravatar.php
> +					return 'https://www.gravatar.com/avatar/' . urlencode($hash) . '?s=' . $size . '&d=' . urlencode($this->defaultIcon);
Myslím, že funkce `http_build_query()` bude parametry encodovat automaticky správně, protože je navržena na bezpečné skládání URL.

2021-08-11 08:38 UTC, merged